### ISSUE TITLE
请问如何修改版权信息？

### ISSUE THREAD

**Issue by mingfuyan** [chaooo/hexo-theme-BlueLake#103]
请问如何修改版权信息

**Comment by chaooo** [comment]
主题目录下的`_config.yml`
```
#Copyright
copyright: 
  enable: true
  describe: 转载请注明出处
```
