### ISSUE TITLE
配置了category, 没有显示分类模块

### ISSUE THREAD

**Issue by we125182** [chaooo/hexo-theme-BlueLake#23]
配置是正确的，但是没有出现‘分类’模块
``` yml
##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.0

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

...
```
![image](https://cloud.githubusercontent.com/assets/17947588/25650360/ec724570-300e-11e7-9bca-e77eaed20d09.png)
