### ISSUE TITLE
首页文档太多的话，拉得太长，增加一个首页文档列表的分页显示吧。

### ISSUE THREAD

**Issue by dieangel** [chaooo/hexo-theme-BlueLake#7]
如题。
另外，对于分类在边栏显示的话。
建议增加类似二级分类(子类)的显示及设置这样。

**Comment by chaooo** [comment]
首页单篇文章太长的的话，在文章内用`<!-- more -->`来截断；
首页是可以分页的，在站点根目录的配置文件`_config.yml`里添加：
``` yml
# Pagination
pagination_dir: page
index_generator:
  per_page: 8 #每页显示8篇文章
archive_generator:
  per_page: 0  #设置为零不分页
  yearly: true
  monthly: true
tag_generator:
  per_page: 0
```
增加类似二级分类的话有时间再研究吧，或者您也可以pull request。
