### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by xiaoxiaotaoya** [chaooo/hexo-theme-BlueLake#83]
大佬好：
     最近使用这个主题一段时间了，有一些小建议请大佬抽空看下
（1）上次问的图片排版问题，跟markdown显示位置不一样。
（2）每个文章右下角已经有了阅读更多，建议左下角添加标签，显得更加美观
（3）建议增加代码复制功能
（4）建议归档不要分页
     目前就这些，期待大佬回复。。。

**Comment by chaooo** [comment]
（1）上个Issue有回复，
（2）（3）等有时间试试看，你也可以fork到自己的仓库试验
（4）归档分页是在博客根目录中配置的，与主题无关联，配置如下：（per_page为0时不分页）
```
# Pagination
## Set per_page to 0 to disable pagination
pagination_dir: page
index_generator:
  per_page: 6
archive_generator:
  per_page: 0
  yearly: true
  monthly: true
tag_generator:
  per_page: 0
```
